### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by FlorianBT** [HeapsIO/heaps-doc#3]
There are at least a few occurences where images are missing (listed below).

The md files use an invalud URL relative to the repository. I assume the first version of the doc had an `img` folder at its root.

For instance in the graphics documentation page, invalid URL are : 
- [ ] img/h2d/drawbox.jpg
- [ ] img/h2d/drawtilefill.jpg

The pattern is pretty obvious. Hopefully the original folder is still somewhere in the history.

Missing images

```
https://github.com/HeapsIO/heaps/wiki/Graphics#drawing-graphics
The above code will produce the following - missing image
The above code will produce the following series of tiled logos - missing image

https://github.com/HeapsIO/heaps/wiki/GPU-Particles#customizing-particles
Last sentence of the section - missing image

https://github.com/HeapsIO/heaps/wiki/Materials#material-basics
Sentence right after the first sample - missing image
Sentence right after the seconde sampl - missing image

https://github.com/HeapsIO/heaps/wiki/Materials#blend-modes
Last sentence right after the sample - missing image 
```

**Comment by markknol** [comment]
The images are just there?  
https://heaps.io/documentation/materials.html

They are part of the website generator.

**Comment by FlorianBT** [comment]
Indeed, this issue is no longer relevant as the website has changed since. At the time, this issue was observed from within github "wiki" documentation. It seems fixed. Thanks for pointing it out
