### ISSUE TITLE
Suggestion: Full Game Samples

### ISSUE THREAD

**Issue by VishwasGagrani** [HeapsIO/heaps-doc#33]
Sources:
* https://heaps.io/documentation/full-game-samples.html

**Comment by ncannasse** [comment]
I am not sure I understand exactly what you are suggesting ?

**Comment by VishwasGagrani** [comment]
Oh Sorry. I was trying to report a bug in the game, but later found out I was looking it wrong. I don't know how this got posted. Please close this thread.
