### ISSUE TITLE
Suggestion: Installation

### ISSUE THREAD

**Issue by trackiss** [HeapsIO/heaps-doc#60]
typo:

```diff
haxelib install hlopenal
- haxelib install hsdl
+ haxelib install hlsdl
haxelib install hldx
```

Sources:
* https://heaps.io/documentation/installation.html

**Comment by markknol** [comment]
It's already updated but not deployed https://github.com/HeapsIO/heaps-doc/commit/c09bc2f6e5cfe2165472bcf178bbc8037c146056
