### ISSUE TITLE
Typo: Installation

### ISSUE THREAD

**Issue by lylebrown** [HeapsIO/heaps-doc#62]
On the installation page, the middle line in the additional libraries section reads
`haxelib install hsdl`
and it should read
`haxelib install hlsdl`

(I was going to fix this myself in a fork, but it appeared correct there, so perhaps the build of the help docs needs to be updated?)

Sources:
* https://heaps.io/documentation/installation.html

**Comment by Skribbles64** [comment]
I don't see the problem, perhaps it has been fixed since this post:
![image](https://user-images.githubusercontent.com/94587115/206308966-09e7e053-f0bc-4aa7-a0ab-082c0caaf075.png)
