### ISSUE TITLE
Suggestion: Hello Hashlink line purpose table for compile.hxml borked

### ISSUE THREAD

**Issue by mininmobile** [HeapsIO/heaps-doc#63]
the markdown file looks fine in gitub but it is broken on the actual documentation page.
![image](https://user-images.githubusercontent.com/17964901/106504916-79cde580-64bf-11eb-826e-16c7e900f9ed.png)

there's also an inconsistency where the Hello World tutorial uses a list for the line purpose and this Hello HashLink tutorial uses a table, it should be one or the other.

Sources:
* https://heaps.io/documentation/hello-hashlink.html
* https://github.com/HeapsIO/heaps-doc/blob/master/Hello-HashLink.md

**Comment by ncannasse** [comment]
Fixed : I think our markdown renderer does not support tables.
