### ISSUE TITLE
Suggestion: Hello World

### ISSUE THREAD

**Issue by angelinim** [HeapsIO/heaps-doc#64]
Sources:
* https://heaps.io/documentation/hello-world.html

I was going through the hello world tutorial and got an error in the compile.hxml file. The error was:
 `Invalid commandline class : Main should be src.Main`

so the compile.hxml needs to be changed to:

```
-cp src
-lib heaps
-js hello.js
-main src.Main
-debug
```

It tells you how to fix it in the error, so it's not a huge deal; just thought I'd mention it.

**Comment by markknol** [comment]
That's not correct, you need to use `-main Main` instead of `-main src.Main`

**Comment by angelinim** [comment]
That makes sense. I wonder what I did wrong. The only way I could get it working was if I used `src.Main`. 

Thanks for the explanation I'll have to go back and look through my code.
