### ISSUE TITLE
Suggestion: Hello World

### ISSUE THREAD

**Issue by jmrepetti** [HeapsIO/heaps-doc#69]
Sources:
* https://heaps.io/documentation/hello-world.html

It's possible to have a simple command line to execute/compile the project from the command line? I'm in OSX and just want to give a try and I can't run the example. 

Thanks!

**Comment by brettchalupa** [comment]
You can run these commands instead of using the VS Code launch task:

1. `haxe compile.xml` -- that'll build the app
2. `open index.html` -- that'll open the HTML file that loads the JS with the game

There may be some other options and args that are helpful, but that'll at least get it running.
