### ISSUE TITLE
Suggestion: Displaying text

### ISSUE THREAD

**Issue by Magnesus** [HeapsIO/heaps-doc#74]
Sources:
* https://heaps.io/documentation/text.html

Hiero links have moved to this address: https://libgdx.com/dev/tools/

**Comment by biskwikman** [comment]
The links for Heaps usage of Distance Field Fonts and Hiero also seem to be dead. They are the 2nd are 3rd link in this image:
![Screenshot from 2022-02-17 00-21-10](https://user-images.githubusercontent.com/17582234/154296554-dbe3303d-fb4c-4aaa-a6ef-9da877ae2e6a.png)

https://heaps.io/libgdx/libgdx/wiki/Distance-field-fonts
https://heaps.io/libgdx/libgdx/wiki/Hiero

**Comment by biskwikman** [comment]
I made a pull request ( #76 ) to fix the link 1st link in the image above. It goes to the libgdx page for Hiero:
https://libgdx.com/wiki/tools/hiero
