### ISSUE TITLE
DOMKIT / Using Heaps Components / Unsupported code block error

### ISSUE THREAD

**Issue by jcward** [HeapsIO/heaps-doc#92]
I believe the domkit example will throw `Unsupported code block` --

```
    static var SRC = 
        <sample-view layout="vertical"> 
            Hello World! 
            <bitmap src={tile} public id="mybmp"/>
        </sample-view>
```

A text node seems to fix it:

```
  static var SRC =
      <sample-view layout="vertical">
          <text text={ "Hello World!" }/>
          <bitmap src={tile} public id="mybmp"/>
      </sample-view>
```

Sources:
* https://heaps.io/documentation/domkit.html

**Comment by alimoeeny** [comment]
This is still a problem. Any pointers to what maybe the root cause?

**Comment by ncannasse** [comment]
It was a change in specification, we did change the documentation but the website auto update is not working anymore (ping @markknol )

**Comment by hristo-kanchev** [comment]
Yeah, it was rather confusing that the docs from the website were outdated. Thankfully people on Discord pointed this out. <3

**Comment by yuxiaomao** [comment]
Wiki is now sync to the website !
